### ISSUE TITLE
How to cite? 

### ISSUE THREAD

**Issue by bethac07** [biovoxxel/BioVoxxel-Figure-Tools#1]
Hi,

Is there a way I can currently cite this tool? Thanks!

~Beth

**Comment by biovoxxel** [comment]
Hi Beth @bethac07 ,

I will make a release tomorrow and push it to zenodo to create a DOI to make it separately citable.
Since I distribute it currently together with the BioVoxxel toolbox, I first thought, people could cite it all together.
But thinking it over, it might make more sense to have a separate DOI for the repository even it distributes together with the other tools.
How do you and your colleagues generally handle those releases citation wise? Any suggestion which option makes more sense?

**Comment by bethac07** [comment]
I think either one is fine! My naive assumption was that since on Fiji it was listed as a separate "plugin", that you would prefer it to have a separate citation, but I can cite the general toolbox if that makes your life easier.

**Comment by biovoxxel** [comment]
Dear @bethac07 ,
Now the figure tools can be cited separately from the toolbox plugins with the following zenodo DOI:

[![DOI](https://zenodo.org/badge/542074524.svg)](https://zenodo.org/badge/latestdoi/542074524)

This is also mentioned on the corresponding ImageJ wiki page

https://imagej.net/plugins/biovoxxel-toolbox#how-to-cite
